stages:
  - deploy
deploy:
  stage: deploy
  tags:
    - saas-windows-medium-amd64
  before_script:
    - Invoke-WebRequest -Uri "https://dot.net/v1/dotnet-install.ps1" -OutFile "dotnet-install.ps1"
    - ./dotnet-install.ps1 -Channel 8.0
  script:
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab-ci --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet build --configuration Release
    - dotnet pack -p:Version=${CI_COMMIT_TAG}
    - cd bin\Release\
    - dotnet nuget push *.nupkg --source gitlab-ci
  only:
    - tags